# **1.Import Libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from scipy import stats

# **2.Import Dataset**

In [ ]:
df = pd.read_csv('/content/netflix_titles.csv')

# **3.Data Understanding**

In [ ]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

## View Information

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8154 entries, 0 to 8153
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8154 non-null   object
 1   type          8154 non-null   object
 2   title         8154 non-null   object
 3   director      5636 non-null   object
 4   cast          7407 non-null   object
 5   country       7351 non-null   object
 6   date_added    8145 non-null   object
 7   release_year  8154 non-null   int64
 8   rating        8150 non-null   object
 9   duration      8150 non-null   object
 10  listed_in     8153 non-null   object
 11  description   8153 non-null   object
dtypes: int64(1), object(11)
memory usage: 764.6+ KB

## Rows & column count

In [ ]:
df.shape

(8154, 12)

## View Column Names

In [ ]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

## View Null values

In [ ]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

## View Duplicate Values

In [ ]:
df.duplicated().sum()

np.int64(0)

# **4.Data Cleaning**

# Why Data Cleaning?
*  Cleaning removes errors → gives accurate insights
*  It handles missing (null) data properly
*  It improves accuracy of analysis
*  It helps in getting better and reliable insights

## Handling Null values

In [ ]:
# Missing values fill
df.fillna("Unknown", inplace=True)

# 1. Director → "Unknown"
df['director'] = df['director'].fillna("Unknown")

# 2. Cast → "unknown"
df['cast'] = df['cast'].fillna("unknown")

# 3. Country → "unknown"
df['country'] = df['country'].fillna("unknown")

# 4. Date Added → Convert + Mode
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

# Fill missing with most frequent date
df['date_added'] = df['date_added'].fillna(df['date_added'].mode()[0])

# 5. Rating → Mode
df['rating'] = df['rating'].fillna(df['rating'].mode()[0])

# 6. Duration → "unknown"
df['duration'] = df['duration'].fillna("unknown")

## After Handling Null values

In [ ]:
print(df.isnull().sum())

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

## Data Type Converstion

In [ ]:
df.dtypes

show_id                 object
type                    object
title                   object
director                object
cast                    object
country                 object
date_added      datetime64[ns]
release_year             int64
rating                  object
duration                object
listed_in               object
description             object
dtype: object

In [ ]:
# Convert release_year (int) → datetime
df['release_year'] = pd.to_datetime(df['release_year'], format='%Y')

## After Converting Data-Types

In [ ]:
df.dtypes

show_id                 object
type                    object
title                   object
director                object
cast                    object
country                 object
date_added      datetime64[ns]
release_year    datetime64[ns]
rating                  object
duration                object
listed_in               object
description             object
dtype: object

# **5.Finding Outliers**

# Why Outlier


*   Outliers are extreme or unusual values in the dataset
*   They can distort analysis results (like average and trends)
*  Handling them helps improve accuracy and reliability of insights

In [ ]:
 # Select numeric columns
num_cols = ['release_year']

# Loop through columns and plot boxplot
for col in num_cols:
    fig = px.box(df, y=col, title=f"{col} Outliers")
    fig.show()

## Fix Outliers

In [ ]:
# Calculate quartiles
Q1 = df['release_year'].quantile(0.25)
Q3 = df['release_year'].quantile(0.75)

# IQR formula
IQR = Q3 - Q1

# Filter data
df = df[(df['release_year'] >= Q1 - 1.5 * IQR) &
        (df['release_year'] <= Q3 + 1.5 * IQR)]

# Outliers in Box Plot

In [ ]:
# Box plot for release year
fig = px.box(df, y='release_year',
             title="Box Plot - Release Year")

fig.show()

## Z-Score

# Why Z-Score


*   It helps identify outliers by measuring how far a value is from the mean
*   It standardizes data, making values comparable across different scales
*  It improves data analysis and model accuracy by detecting unusual values

In [ ]:
# Calculate Z-score

# Convert to numeric
df['release_year'] = pd.to_numeric(df['release_year'], errors='coerce')

# Calculate Z-score
df['z_score'] = np.abs(stats.zscore(df['release_year'].dropna()))

# View result
df[['release_year', 'z_score']].head()

/tmp/ipykernel_1184/3809049252.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_1184/3809049252.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

          release_year   z_score
0  1577836800000000000  0.988495
1  1609459200000000000  1.263999
2  1609459200000000000  1.263999
3  1609459200000000000  1.263999
4  1609459200000000000  1.263999

# **6.Statistics(EDA)**

## Univariate


*   Used to analyze one variable at a time
*  Helps understand distribution, pattern, and summary (mean, median)

In [ ]:
px.histogram(df, x='release_year',
             title="Distribution of Release Year").show()

## Bivariate Analysis


*   Used to study relationship between two variables
*  Helps find correlation or association (e.g., sales vs profit)

In [ ]:
# Convert date_added to datetime
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

# Create year_added column
df['year_added'] = df['date_added'].dt.year

/tmp/ipykernel_1184/702648743.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_1184/702648743.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
px.scatter(df,
           x='release_year',
           y='year_added',
           title="Release Year vs Year Added").show()

## Multivariate Analysis

*   Used to analyze more than two variables together
*  Helps understand complex relationships and overall patterns

In [ ]:
px.scatter(df,
           x='release_year',
           y='year_added',
           color='type',
           title="Multi-variable Analysis").show()

# **7.Correlation**

# Why Correlation


*   It shows the relationship between variables
It indicates the strength and direction (positive/negative)
*  It helps in better predictions and decision making

In [ ]:
px.scatter(df, x='release_year', y='year_added', title="Correlation: Release Year vs Year Added").show()

# **8.Trend Analysis**

# Why Trend Analysis


*   Steady Growth – Content additions increase gradually over time, showing platform expansion.
*  Peak Years – Some years show a sharp spike, meaning highest content upload happened in those periods.
*  Recent Decline or Stabilization – Latest years may show a slight drop or flattening, possibly due to incomplete data or reduced additions.
*  Modern Content Focus – Most content is added in recent years, indicating a focus on newer releases rather than old ones.

In [ ]:
# Count values per year
trend = df['year_added'].value_counts().sort_index()

# Line chart
fig = px.line(trend,
              title="Content Trend Over Years")

fig.show()

# Insights


*   Content growth increases over time, showing expansion of the platform
*  A peak year indicates the highest content addition (maximum growth phase)
* Recent years may show slight decline or fluctuation due to market or strategy changes
* Overall trend suggests a focus on modern and recent content rather than older releases

# **9.Hypothesis Testing**

# why Hypothesis


*   Testing Assumptions – A hypothesis helps you check if your idea or assumption about data is true or false.
* Decision Making – It provides a logical base to accept or reject a claim using statistical methods.
* Finding Relationships – Helps identify whether there is a meaningful connection between variables (e.g., correlation or impact).

In [ ]:
# Separate data
movie = df[df['type'] == 'Movie']['release_year']
tv = df[df['type'] == 'TV Show']['release_year']

# Perform t-test
t_stat, p_value = stats.ttest_ind(movie, tv)

print("P-value:", p_value)

P-value: 2.2960670909571806e-58

# **10.Probability**

# why Probability


*   Measure Uncertainty – Probability helps you understand how likely an event is to happen.
*  Better Decisions – It supports decision-making in situations where outcomes are not certain.
*  Predict Outcomes – Used to estimate future events based on patterns in data.

In [ ]:
# Probability of movie
prob_movie = len(df[df['type'] == "Movie"]) / len(df)

print("Probability of Movie:", prob_movie)

Probability of Movie: 0.6769690927218345

# **10.Sampling Techniques**

# Why Sampling


*   Saves Time & Cost – Studying a small sample is faster and cheaper than analyzing the entire population.
*  Easy to Handle Data – Working with a sample makes data analysis more manageable and efficient.
*  Good Representation – A properly selected sample can accurately reflect the whole population.

In [ ]:
sample = df.sample(frac=0.2, random_state=1)

sample.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,z_score,year_added
3201,s3202,Movie,Thug Life,Mukesh Vohra,"Harish Verma, Jass Bajwa, Rajiv Thakur, Ihana ...",India,2019-12-01,1483228800000000000,TV-14,133 min,"Comedies, Dramas, International Movies",A get-rich-quick scheme goes awry when a group...,0.164242,2019
493,s494,TV Show,RESIDENT EVIL: Infinite Darkness,Unknown,"Nick Apostolides, Stephanie Panisello, Ray Cha...","United States, Japan",2021-07-08,1609459200000000000,TV-MA,1 Season,"Anime Series, TV Horror, TV Thrillers","Years after the horrors of Raccoon City, Leon ...",1.263999,2021
119,s120,Movie,Here and There,JP Habac,"Janine Gutierrez, JC Santos, Victor Anastacio,...",Unknown,2021-09-02,1577836800000000000,TV-MA,99 min,"Dramas, International Movies, Romantic Movies",After meeting through a heated exchange on soc...,0.988495,2021
3442,s3443,Movie,The Spooky Tale of Captain Underpants Hack-a-ween,Unknown,"Nat Faxon, Jay Gragnani, Ramone Hamilton, Sean...",United States,2019-10-08,1546300800000000000,TV-Y7,46 min,"Children & Family Movies, Comedies","When Melvin tries to cancel Halloween, clever ...",0.713744,2019
1853,s1854,Movie,Rooting for Roona,"Pavitra Chalam, Akshay Shankar",Unknown,India,2020-10-15,1577836800000000000,TV-PG,42 min,"Documentaries, International Movies","In rural India, a child with hydrocephalus get...",0.988495,2020

# **11.Combined charts**

In [ ]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=2, cols=2,
                   subplot_titles=("Movies vs TV Shows",
                                   "Top 5 Countries",
                                   "Content Added Over Years",
                                   "Ratings Distribution"))

# 1.Movies vs TV Shows Distribution
type_counts = df['type'].value_counts()
fig.add_trace(go.Bar(x=type_counts.index, y=type_counts.values),
              row=1, col=1)

# 2.Top 5 Content Producing Countries
country_counts = df['country'].value_counts().head(5)
fig.add_trace(go.Bar(x=country_counts.index, y=country_counts.values),
              row=1, col=2)

# 3.Year-wise Content Added Trend
year_counts = df['year_added'].value_counts().sort_index()
fig.add_trace(go.Scatter(x=year_counts.index, y=year_counts.values,
                         mode='lines+markers'),
              row=2, col=1)

# 4.Ratings Distribution Analysis
rating_counts = df['rating'].value_counts()
fig.add_trace(go.Bar(x=rating_counts.values, y=rating_counts.index,
                     orientation='h'),
              row=2, col=2)

fig.update_layout(height=800, width=1000,
                  title_text="Combined EDA Dashboard")

fig.show()

# Insights
*  Movies are more than TV Shows
*  USA and India produce most content
*  Content sharply increased after 2015
*  TV-MA is the most common rating

# **12.Automation**

# why Automation


*   Saves Time – Repetitive tasks are done quickly without manual effort.
*  Reduces Errors – Minimizes human mistakes and improves accuracy.
*  Increases Efficiency – Handles large data and processes faster and more consistently.

In [ ]:
import pandas as pd
import numpy as np
from scipy import stats
import plotly.express as px

def auto_data_analysis(df):

    print("🔹 Initial Shape:", df.shape)

    # -------------------------------
    # 1. DATA CLEANING
    # -------------------------------
    print("\n Data Cleaning")
    df.columns = df.columns.str.strip()

    # -------------------------------
    # 2. REMOVE DUPLICATES
    # -------------------------------
    print("\n Removing Duplicates")
    df = df.drop_duplicates()
    print("After removing duplicates:", df.shape)

    # -------------------------------
    # 3. NULL VALUES + HANDLING
    # -------------------------------
    print("\n Handling Missing Values")

    for col in df.columns:
        if df[col].dtype == 'object':
            df[col] = df[col].fillna("Unknown")
        else:
            df[col] = df[col].fillna(df[col].median())

    print(df.isnull().sum())

    # -------------------------------
    # 4. DATA TYPE CONVERSION
    # -------------------------------
    print("\n Data Type Conversion")

    for col in df.columns:
        try:
            df[col] = pd.to_numeric(df[col])
        except:
            pass

    print(df.dtypes)

    # -------------------------------
    # 5. OUTLIER DETECTION (Z-SCORE)
    # -------------------------------
    print("\n Outlier Detection")

    num_cols = df.select_dtypes(include=np.number).columns

    for col in num_cols:
        z = np.abs(stats.zscore(df[col], nan_policy='omit'))
        df = df[z < 3]

    print("After removing outliers:", df.shape)

    # -------------------------------
    # 6. TREND ANALYSIS
    # -------------------------------
    print("\n Trend Analysis")

    for col in num_cols:
        try:
            trend = df[col].value_counts().sort_index()
            px.line(trend, title=f"Trend - {col}").show()
        except:
            pass

    # -------------------------------
    # 7. HYPOTHESIS TESTING
    # -------------------------------
    print("\n Hypothesis Testing")

    if len(num_cols) >= 2:
        col1 = num_cols[0]
        col2 = num_cols[1]

        t, p = stats.ttest_ind(df[col1], df[col2])

        print(f"T-test between {col1} & {col2}")
        print("P-value:", p)

    else:
        print("Not enough numeric columns for hypothesis testing")

    print("\n Process Completed")

    return df


# -------------------------------
#  RUN FOR ANY DATASET
# -------------------------------
df = pd.read_csv("netflix_titles.csv")

df_clean = auto_data_analysis(df)

🔹 Initial Shape: (8807, 12)

 Data Cleaning

 Removing Duplicates
After removing duplicates: (8807, 12)

 Handling Missing Values
show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

 Data Type Conversion
show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

 Outlier Detection
After removing outliers: (8590, 12)

 Trend Analysis

 Hypothesis Testing
Not enough numeric columns for hypothesis testing

 Process Completed

In [ ]:
# function definition
def eda_pipeline(file_path):
    df = pd.read_csv(file_path)
    print("Data Loaded Successfully")
    return df

# function call
clean_df = eda_pipeline("/content/netflix_titles.csv")

Data Loaded Successfully

# Ingights



*   Clean Dataset – Duplicates and missing values are handled, so data is reliable.
*  Improved Accuracy – Outliers removed using Z-score, reducing extreme value impact.
*  Structured Data – Data types converted properly, making analysis easier.
*  Growth Trend – Data shows increasing trend over time, indicating expansion (e.g., more content added in recent years).
*  Peak Patterns – Some values appear more frequently, showing high concentration in specific years or categories.
*  Statistical Result – T-test helps identify if two variables have a significant difference (based on p-value).

# **13.Sweetviz**

# Why Sweetviz



*   Automatic EDA Reports – Generates complete data analysis reports instantly without much coding.
*  Easy Visualization – Shows charts, distributions, and relationships in a clear and interactive way.
* Saves Time – Quickly identifies patterns, missing values, and correlations, speeding up analysis.

In [ ]:
pip install sweetviz

Collecting sweetviz
  Downloading sweetviz-2.3.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (2.2.2)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (2.0.2)
Requirement already satisfied: matplotlib>=3.1.3 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (3.10.0)
Requirement already satisfied: tqdm>=4.43.0 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (4.67.3)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (1.16.3)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (3.1.6)
Requirement already satisfied: importlib_resources>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (6.5.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.11.1->sweetviz) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Downloading sweetviz-2.3.3-py3-none-any.whl (15.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 85.3 MB/s eta 0:00:00
Installing collected packages: sweetviz
Successfully installed sweetviz-2.3.3

In [ ]:
import pandas as pd
import sweetviz as sv

df = pd.read_csv(
    "/content/netflix_titles.csv",
    engine='python',
    encoding='latin1',
    on_bad_lines='skip'
)

report = sv.analyze(df)

# IMPORTANT LINE 👇
report.show_html("report.html")

                                             |          | [  0%]   00:00 -> (? left)

Report report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

# **Final Insights**
*   Dataset is clean and ready after removing duplicates and handling missing values.
*  Most content is from recent years, showing strong growth and modern focus.
*  Outliers were removed, improving data accuracy and reliability.
*  Trend analysis shows peaks in certain years, indicating uneven content addition.
*  Statistical tests help understand relationships between variables.


# **Recommendations**
*   Focus more on recent trending content to increase engagement.
*  Add more regional and diverse content to reach wider audiences.
*  Study peak years to understand what caused high growth.
*  Maintain regular data cleaning for better analysis quality.
*  Use statistical insights for better business and content decisions.